[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
aetherment = {path = "../aetherment"}
eframe = {version = "0.22.0", default-features = false, features = ["accesskit", "default_fonts", "wgpu"]}